export const DASHBOARD_SUMMARY_REQUEST = "DASHBOARD_SUMMARY_REQUEST";
export const DASHBOARD_SUMMARY_SUCCESS = "DASHBOARD_SUMMARY_SUCCESS";
export const DASHBOARD_SUMMARY_FAILURE = "DASHBOARD_SUMMARY_FAILURE";
