export const SETTING_FETCH_REQUEST = "SETTING_FETCH_REQUEST";
export const SETTING_FETCH_SUCCESS = "SETTING_FETCH_SUCCESS";
export const SETTING_FETCH_FAILURE = "SETTING_FETCH_FAILURE";

export const SETTING_UPDATE_REQUEST = "SETTING_UPDATE_REQUEST";
export const SETTING_UPDATE_SUCCESS = "SETTING_UPDATE_SUCCESS";
export const SETTING_UPDATE_FAILURE = "SETTING_UPDATE_FAILURE";
