export const LEDGER_LIST_REQUEST = "LEDGER_LIST_REQUEST";
export const LEDGER_LIST_SUCCESS = "LEDGER_LIST_SUCCESS";
export const LEDGER_LIST_FAILURE = "LEDGER_LIST_FAILURE";

export const LEDGER_SAVE_REQUEST = "LEDGER_SAVE_REQUEST";
export const LEDGER_SAVE_SUCCESS = "LEDGER_SAVE_SUCCESS";
export const LEDGER_SAVE_FAILURE = "LEDGER_SAVE_FAILURE";

export const LEDGER_DELETE_REQUEST = "LEDGER_DELETE_REQUEST";
export const LEDGER_DELETE_SUCCESS = "LEDGER_DELETE_SUCCESS";
export const LEDGER_DELETE_FAILURE = "LEDGER_DELETE_FAILURE";
