export const GUEST_LIST_REQUEST = "GUEST_LIST_REQUEST";
export const GUEST_LIST_SUCCESS = "GUEST_LIST_SUCCESS";
export const GUEST_LIST_FAILURE = "GUEST_LIST_FAILURE";

export const GUEST_SAVE_REQUEST = "GUEST_SAVE_REQUEST";
export const GUEST_SAVE_SUCCESS = "GUEST_SAVE_SUCCESS";
export const GUEST_SAVE_FAILURE = "GUEST_SAVE_FAILURE";

export const GUEST_DELETE_REQUEST = "GUEST_DELETE_REQUEST";
export const GUEST_DELETE_SUCCESS = "GUEST_DELETE_SUCCESS";
export const GUEST_DELETE_FAILURE = "GUEST_DELETE_FAILURE";
