export const NOTIFICATION_FETCH_REQUEST = "NOTIFICATION_FETCH_REQUEST";
export const NOTIFICATION_FETCH_SUCCESS = "NOTIFICATION_FETCH_SUCCESS";
export const NOTIFICATION_FETCH_FAILURE = "NOTIFICATION_FETCH_FAILURE";

export const NOTIFICATION_MARK_READ_SUCCESS = "NOTIFICATION_MARK_READ_SUCCESS";
export const NOTIFICATION_MARK_ALL_READ_SUCCESS = "NOTIFICATION_MARK_ALL_READ_SUCCESS";
export const NOTIFICATION_REMOVE_SUCCESS = "NOTIFICATION_REMOVE_SUCCESS";
