import type {
  EventItem,
  GuestItem,
  GuestProfile,
  VendorItem,
  MoiItem,
} from "./types";

export const events: EventItem[] = [
  {
    id: "arjun-priya-wedding",
    name: "Arjun & Priya Wedding",
    type: "Wedding Celebration",
    typeKey: "weddingCelebration",
    date: "2026-08-18",
    time: "6:00 PM",
    weekday: "Tue",
    location: "Chennai",
    venue: "Grand Palace",
    guests: 342,
    status: "confirmed",
    image:
      "https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=500&auto=format&fit=crop",
  },
  {
    id: "ananyas-birthday",
    name: "Ananya's Birthday",
    type: "Birthday Celebration",
    typeKey: "birthdayCelebration",
    date: "2026-09-05",
    time: "5:00 PM",
    weekday: "Sat",
    location: "Chennai",
    venue: "Luxe Resort",
    guests: 86,
    status: "planning",
    image:
      "https://images.unsplash.com/photo-1464349153735-7db50ed83c84?q=80&w=500&auto=format&fit=crop",
  },
  {
    id: "25th-anniversary",
    name: "25th Anniversary",
    type: "Anniversary Celebration",
    typeKey: "anniversaryCelebration",
    date: "2026-09-22",
    time: "7:00 PM",
    weekday: "Tue",
    location: "Coimbatore",
    venue: "Green Valley",
    guests: 54,
    status: "savedate",
    image:
      "https://images.unsplash.com/photo-1478146059778-26028b07395a?q=80&w=500&auto=format&fit=crop",
  },
  {
    id: "annual-meet-2026",
    name: "Annual Meet 2026",
    type: "Corporate Event",
    typeKey: "corporateEvent",
    date: "2026-10-10",
    time: "10:00 AM",
    weekday: "Sat",
    location: "Chennai",
    venue: "Business Club",
    guests: 120,
    status: "confirmed",
    image:
      "https://images.unsplash.com/photo-1511578314322-379afb476865?q=80&w=500&auto=format&fit=crop",
  },
  {
    id: "family-get-together",
    name: "Family Get Together",
    type: "Family Celebration",
    typeKey: "familyCelebration",
    date: "2026-10-28",
    time: "5:30 PM",
    weekday: "Wed",
    location: "Erode",
    venue: "Maple Hall",
    guests: 63,
    status: "planning",
    image:
      "https://images.unsplash.com/photo-1529636798458-92182e662485?q=80&w=500&auto=format&fit=crop",
  },
];

export const guests: GuestItem[] = [
  {
    id: "ramesh-kumar",
    name: "Ramesh Kumar",
    relation: "Family",
    group: "family",
    phone: "+91 98765 43210",
    email: "ramesh@gmail.com",
    eventName: "Arjun & Priya Wedding",
    eventDate: "18 Aug 2026",
    status: "attending",
  },
  {
    id: "priya-nair",
    name: "Priya Nair",
    relation: "Friend",
    group: "friends",
    phone: "+91 91234 56789",
    email: "priya.nair@gmail.com",
    eventName: "Arjun & Priya Wedding",
    eventDate: "18 Aug 2026",
    status: "pending",
  },
  {
    id: "karthik-iyer",
    name: "Karthik Iyer",
    relation: "Colleague",
    group: "colleagues",
    phone: "+91 90987 76655",
    email: "karthik.iyer@gmail.com",
    eventName: "Annual Meet 2026",
    eventDate: "10 Oct 2026",
    status: "attending",
  },
  {
    id: "meena-krishnan",
    name: "Meena Krishnan",
    relation: "Family",
    group: "family",
    phone: "+91 93456 78123",
    email: "meena.k@gmail.com",
    eventName: "Family Get Together",
    eventDate: "28 Oct 2026",
    status: "notattending",
  },
  {
    id: "suresh-babu",
    name: "Suresh Babu",
    relation: "Relatives",
    group: "relatives",
    phone: "+91 97070 24600",
    email: "suresh.babu@gmail.com",
    eventName: "25th Anniversary",
    eventDate: "22 Sep 2026",
    status: "pending",
  },
];

export const guestProfiles: Record<string, GuestProfile> = {
  "ramesh-kumar": {
    avatar: "R",
    name: "Ramesh Kumar",
    relation: "Family",
    relationDetail: "Uncle (Bride side)",
    attendance: "attending",
    phone: "+91 98765 43210",
    email: "ramesh@gmail.com",
    address: "12, Lake View Road, T. Nagar",
    city: "Chennai, Tamil Nadu",
    category: "Family",
    people: "3",
    invite: "Sent · Confirmed",
    notes: "Prefers vegetarian meals. Bringing children.",
    moiTotal: "₹22,500",
    moiBreakdown: [
      { icon: "💰", label: "Cash", value: "₹10,000" },
      { icon: "📱", label: "UPI", value: "₹5,000" },
      { icon: "🌟", label: "Gold", value: "8g" },
      { icon: "🥈", label: "Silver", value: "—" },
      { icon: "🎁", label: "Gifts", value: "2" },
      { icon: "👕", label: "Clothes", value: "1 set" },
      { icon: "🎫", label: "Vouchers", value: "₹2,000" },
      { icon: "✨", label: "Other", value: "₹500" },
    ],
    history: [
      { icon: "💰", title: "Cash · ₹10,000", subtitle: "Arjun & Priya Wedding · 18 Aug 2026" },
      { icon: "📱", title: "UPI · ₹5,000", subtitle: "Arjun & Priya Wedding · 17 Aug 2026" },
      { icon: "🌟", title: "Gold chain · 8g", subtitle: "Arjun & Priya Wedding · 16 Aug 2026" },
      { icon: "🎫", title: "Voucher · ₹2,000", subtitle: "Arjun & Priya Wedding · 15 Aug 2026" },
      { icon: "👕", title: "Clothes · 1 set", subtitle: "Arjun & Priya Wedding · 14 Aug 2026" },
    ],
    events: [
      {
        image:
          "https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=200&auto=format&fit=crop",
        name: "Arjun & Priya Wedding",
        date: "18 Aug 2026",
        location: "Chennai",
        status: "attending",
      },
      {
        image:
          "https://images.unsplash.com/photo-1529636798458-92182e662485?q=80&w=200&auto=format&fit=crop",
        name: "Family Get Together",
        date: "28 Oct 2026",
        location: "Erode",
        status: "pending",
      },
    ],
  },
  "priya-nair": {
    avatar: "P",
    name: "Priya Nair",
    relation: "Friends",
    relationDetail: "College friend",
    attendance: "pending",
    phone: "+91 91234 56789",
    email: "priya.nair@gmail.com",
    address: "45, Green Park",
    city: "Chennai, Tamil Nadu",
    category: "Friends",
    people: "2",
    invite: "Sent · Awaiting reply",
    notes: "May arrive late.",
    moiTotal: "₹5,000",
    moiBreakdown: [
      { icon: "💰", label: "Cash", value: "—" },
      { icon: "📱", label: "UPI", value: "₹5,000" },
      { icon: "🌟", label: "Gold", value: "—" },
      { icon: "🥈", label: "Silver", value: "—" },
      { icon: "🎁", label: "Gifts", value: "—" },
      { icon: "👕", label: "Clothes", value: "—" },
      { icon: "🎫", label: "Vouchers", value: "—" },
      { icon: "✨", label: "Other", value: "—" },
    ],
    history: [{ icon: "📱", title: "UPI · ₹5,000", subtitle: "Arjun & Priya Wedding · 17 Aug 2026" }],
    events: [
      {
        image:
          "https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=200&auto=format&fit=crop",
        name: "Arjun & Priya Wedding",
        date: "18 Aug 2026",
        location: "Chennai",
        status: "pending",
      },
    ],
  },
  "karthik-iyer": {
    avatar: "K",
    name: "Karthik Iyer",
    relation: "Colleagues",
    relationDetail: "Work colleague",
    attendance: "attending",
    phone: "+91 90987 76655",
    email: "karthik.iyer@gmail.com",
    address: "88, IT Corridor",
    city: "Chennai, Tamil Nadu",
    category: "Colleagues",
    people: "1",
    invite: "Sent · Confirmed",
    notes: "",
    moiTotal: "₹15,000",
    moiBreakdown: [
      { icon: "💰", label: "Cash", value: "—" },
      { icon: "📱", label: "UPI", value: "—" },
      { icon: "🌟", label: "Gold", value: "—" },
      { icon: "🥈", label: "Silver", value: "250g" },
      { icon: "🎁", label: "Gifts", value: "—" },
      { icon: "👕", label: "Clothes", value: "—" },
      { icon: "🎫", label: "Vouchers", value: "—" },
      { icon: "✨", label: "Other", value: "—" },
    ],
    history: [{ icon: "🥈", title: "Silver set · 250g", subtitle: "Arjun & Priya Wedding · 15 Aug 2026" }],
    events: [
      {
        image:
          "https://images.unsplash.com/photo-1511578314322-379afb476865?q=80&w=200&auto=format&fit=crop",
        name: "Annual Meet 2026",
        date: "10 Oct 2026",
        location: "Chennai",
        status: "attending",
      },
    ],
  },
  "meena-krishnan": {
    avatar: "M",
    name: "Meena Krishnan",
    relation: "Family",
    relationDetail: "Aunt",
    attendance: "notattending",
    phone: "+91 93456 78123",
    email: "meena.k@gmail.com",
    address: "7, Temple Street",
    city: "Erode, Tamil Nadu",
    category: "Family",
    people: "0",
    invite: "Sent · Declined",
    notes: "Unable to attend due to travel.",
    moiTotal: "₹2,000",
    moiBreakdown: [
      { icon: "💰", label: "Cash", value: "—" },
      { icon: "📱", label: "UPI", value: "—" },
      { icon: "🌟", label: "Gold", value: "—" },
      { icon: "🥈", label: "Silver", value: "—" },
      { icon: "🎁", label: "Gifts", value: "—" },
      { icon: "👕", label: "Clothes", value: "—" },
      { icon: "🎫", label: "Vouchers", value: "₹2,000" },
      { icon: "✨", label: "Other", value: "—" },
    ],
    history: [{ icon: "🎫", title: "Voucher · ₹2,000", subtitle: "25th Anniversary · 16 Aug 2026" }],
    events: [
      {
        image:
          "https://images.unsplash.com/photo-1529636798458-92182e662485?q=80&w=200&auto=format&fit=crop",
        name: "Family Get Together",
        date: "28 Oct 2026",
        location: "Erode",
        status: "notattending",
      },
    ],
  },
  "suresh-babu": {
    avatar: "S",
    name: "Suresh Babu",
    relation: "Relatives",
    relationDetail: "Cousin",
    attendance: "pending",
    phone: "+91 97070 24600",
    email: "suresh.babu@gmail.com",
    address: "21, Market Road",
    city: "Coimbatore, Tamil Nadu",
    category: "Relatives",
    people: "4",
    invite: "Sent · Awaiting reply",
    notes: "Family of 4.",
    moiTotal: "₹8,000",
    moiBreakdown: [
      { icon: "💰", label: "Cash", value: "₹5,000" },
      { icon: "📱", label: "UPI", value: "—" },
      { icon: "🌟", label: "Gold", value: "—" },
      { icon: "🥈", label: "Silver", value: "—" },
      { icon: "🎁", label: "Gifts", value: "—" },
      { icon: "👕", label: "Clothes", value: "—" },
      { icon: "🎫", label: "Vouchers", value: "—" },
      { icon: "✨", label: "Other", value: "₹3,000" },
    ],
    history: [{ icon: "💰", title: "Cash · ₹5,000", subtitle: "25th Anniversary · 17 Aug 2026" }],
    events: [
      {
        image:
          "https://images.unsplash.com/photo-1478146059778-26028b07395a?q=80&w=200&auto=format&fit=crop",
        name: "25th Anniversary",
        date: "22 Sep 2026",
        location: "Coimbatore",
        status: "pending",
      },
    ],
  },
};

export const vendors: VendorItem[] = [
  {
    id: "royal-caterers",
    name: "Royal Caterers",
    category: "Catering",
    categoryKey: "catCatering",
    rating: 4.8,
    reviews: 124,
    phone: "+91 90765 43210",
    location: "Chennai",
    status: "confirmed",
    statusLabelKey: "statusBooked",
    image:
      "https://images.unsplash.com/photo-1555244162-803834f70033?q=80&w=500&auto=format&fit=crop",
  },
  {
    id: "grand-palace",
    name: "Grand Palace",
    category: "Venue",
    categoryKey: "catVenueChip",
    rating: 4.7,
    reviews: 98,
    phone: "+91 91234 56789",
    location: "Chennai",
    status: "confirmed",
    statusLabelKey: "statusBooked",
    image:
      "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?q=80&w=500&auto=format&fit=crop",
  },
  {
    id: "moments-studio",
    name: "Moments Studio",
    category: "Photography",
    categoryKey: "catPhotography",
    rating: 4.9,
    reviews: 154,
    phone: "+91 93887 76665",
    location: "Chennai",
    status: "confirmed",
    statusLabelKey: "statusBooked",
    image:
      "https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=500&auto=format&fit=crop",
  },
  {
    id: "blossom-decorations",
    name: "Blossom Decorations",
    category: "Decoration",
    categoryKey: "catDecoration",
    rating: 4.6,
    reviews: 87,
    phone: "+91 91434 70123",
    location: "Chennai",
    status: "planning",
    statusLabelKey: "statusContacted",
    image:
      "https://images.unsplash.com/photo-1478146059778-26028b07395a?q=80&w=500&auto=format&fit=crop",
  },
  {
    id: "rhythm-events",
    name: "Rhythm Events",
    category: "Entertainment",
    categoryKey: "catEntertainment",
    rating: 4.5,
    reviews: 74,
    phone: "+91 97777 24680",
    location: "Chennai",
    status: "savedate",
    statusLabelKey: "statusQuotation",
    image:
      "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?q=80&w=500&auto=format&fit=crop",
  },
  {
    id: "sree-travels",
    name: "Sree Travels",
    category: "Transport",
    categoryKey: "catTransport",
    rating: 4.4,
    reviews: 62,
    phone: "+91 90650 13345",
    location: "Chennai",
    status: "pending",
    statusLabelKey: "statusShortlisted",
    image:
      "https://images.unsplash.com/photo-1494515843206-f3117d3f51b7?q=80&w=500&auto=format&fit=crop",
  },
  {
    id: "dream-lights",
    name: "Dream Lights",
    category: "Lighting",
    categoryKey: "catOthers",
    rating: 4.6,
    reviews: 51,
    phone: "+91 90112 34567",
    location: "Chennai",
    status: "planning",
    statusLabelKey: "statusContacted",
    image:
      "https://images.unsplash.com/photo-1467810563316-b5476525c0f9?q=80&w=500&auto=format&fit=crop",
  },
  {
    id: "audio-pro",
    name: "Audio Pro",
    category: "Sound & AV",
    categoryKey: "catOthers",
    rating: 4.3,
    reviews: 39,
    phone: "+91 90223 45678",
    location: "Chennai",
    status: "pending",
    statusLabelKey: "statusShortlisted",
    image:
      "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=500&auto=format&fit=crop",
  },
];

export const moiContributions: MoiItem[] = [
  {
    id: "moi-1",
    guestName: "Rajesh Kumar",
    eventName: "Arjun & Priya Wedding",
    type: "money",
    method: "cash",
    kindLabel: "💰 Cash",
    amountLabel: "₹10,000",
    amount: 10000,
    date: "2026-08-18",
  },
  {
    id: "moi-2",
    guestName: "Priya & Family",
    eventName: "Arjun & Priya Wedding",
    type: "gift",
    method: "gold",
    kindLabel: "🌟 Gold",
    amountLabel: "Gold chain · 12.5g",
    amount: 0,
    date: "2026-08-18",
  },
  {
    id: "moi-3",
    guestName: "Suresh Babu",
    eventName: "Arjun & Priya Wedding",
    type: "money",
    method: "upi",
    kindLabel: "📱 UPI",
    amountLabel: "₹5,000",
    amount: 5000,
    date: "2026-08-17",
  },
  {
    id: "moi-4",
    guestName: "Meena Krishnan",
    eventName: "25th Anniversary",
    type: "gift",
    method: "voucher",
    kindLabel: "🎫 Voucher",
    amountLabel: "₹2,000 · Lifestyle store",
    amount: 2000,
    date: "2026-08-16",
  },
  {
    id: "moi-5",
    guestName: "Karthik Iyer",
    eventName: "Arjun & Priya Wedding",
    type: "gift",
    method: "silver",
    kindLabel: "🥈 Silver",
    amountLabel: "Silver set · 250g",
    amount: 0,
    date: "2026-08-15",
  },
  {
    id: "moi-6",
    guestName: "Ananya Sharma",
    eventName: "Ananya's Birthday",
    type: "money",
    method: "bank",
    kindLabel: "🏦 Bank Transfer",
    amountLabel: "₹25,000",
    amount: 25000,
    date: "2026-08-14",
  },
];

export const dashboardNotifications = [
  { titleKey: "rsvpPending", subtitleKey: "followUp", icon: "guests" },
  { titleKey: "paymentDueTomorrow", subtitleKey: "forCatering", icon: "ledger" },
  { titleKey: "vendorConfirmedHead", subtitleKey: "momentsStudioAccepted", icon: "vendorConfirmed" },
] as const;

export const dashboardAttention = [
  { titleKey: "rsvpPending", subtitleKey: "followUp", icon: "guestsCheck" },
  { titleKey: "paymentDue35", subtitleKey: "reviewLedger", icon: "ledger" },
  { titleKey: "photographyContract", subtitleKey: "contactVendor", icon: "document" },
  { titleKey: "seatingReview", subtitleKey: "openEvent", icon: "seating" },
] as const;

export const dashboardMoments = [
  { textKey: "momentJoined", timeKey: "minsAgo10", icon: "guests" },
  { textKey: "momentCatering", timeKey: "hourAgo1", icon: "bell" },
  { textKey: "momentPayment", timeKey: "hoursAgo3", icon: "ledger" },
  { textKey: "momentVendor", timeKey: "hoursAgo5", icon: "document" },
  { textKey: "momentAttending", timeKey: "yesterday", icon: "check" },
] as const;

export const ledgerCategories = [
  { labelKey: "catVenue", amount: "₹2,50,000 (29%)" },
  { labelKey: "catCatering", amount: "₹1,80,000 (21%)" },
  { labelKey: "catDecoration", amount: "₹1,40,000 (16%)" },
  { labelKey: "catPhotography", amount: "₹80,000 (9%)" },
  { labelKey: "catEntertainment", amount: "₹1,10,000 (13%)" },
  { labelKey: "catTransport", amount: "₹90,000 (11%)" },
] as const;

export const ledgerTransactions = [
  { title: "₹45,000 — Catering Advance", date: "12 May 2026", status: "paid" as const },
  { title: "₹1,25,000 — Venue Booking", date: "10 May 2026", status: "paid" as const },
  { title: "₹35,000 — Photography Advance", date: "14 May 2026", status: "pending" as const },
  { title: "₹15,000 — Decoration Advance", date: "09 May 2026", status: "paid" as const },
  { title: "₹20,000 — Entertainment Advance", date: "08 May 2026", status: "pending" as const },
];
