export const MOI_LIST_REQUEST = "MOI_LIST_REQUEST";
export const MOI_LIST_SUCCESS = "MOI_LIST_SUCCESS";
export const MOI_LIST_FAILURE = "MOI_LIST_FAILURE";

export const MOI_SAVE_REQUEST = "MOI_SAVE_REQUEST";
export const MOI_SAVE_SUCCESS = "MOI_SAVE_SUCCESS";
export const MOI_SAVE_FAILURE = "MOI_SAVE_FAILURE";

export const MOI_DELETE_REQUEST = "MOI_DELETE_REQUEST";
export const MOI_DELETE_SUCCESS = "MOI_DELETE_SUCCESS";
export const MOI_DELETE_FAILURE = "MOI_DELETE_FAILURE";
